# Generated by Django 3.2.4 on 2021-06-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_onlinegamestore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineGameStore',
        ),
    ]
