# Generated by Django 3.2.4 on 2021-06-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='click edit to change bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='no name', max_length=100),
        ),
    ]
